{% set name = "azure-storage-common" %}
{% set version = "2.1.0" %}
{% set sha256 = "ccedef5c67227bc4d6670ffd37cec18fb529a1b7c3a5e53e4096eb0cf23dc73f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 10
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - azure-common >=1.1.5
    - cryptography
    - python-dateutil
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.storage
    - azure.storage.common

about:
  home: https://github.com/Azure/azure-storage-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Microsoft Azure Storage Common Client Library for Python'

extra:
  recipe-maintainers:
    - xhochy
