{% set name = "azure-storage-common" %}
{% set version = "2.0.0" %}
{% set sha256 = "4390cd5f6fb50fbff37ba154258ea010291a84f128917141e1d7060597bd4708" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - azure-common >=1.1.5
    - cryptography
    - python-dateutil
    - requests

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.common

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  license_family: Apache
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: 'Microsoft Azure Storage Common Client Library for Python'

extra:
  recipe-maintainers:
    - xhochy
