schema_version: 1

context:
  name: azure-storage-common
  version: "2.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ccedef5c67227bc4d6670ffd37cec18fb529a1b7c3a5e53e4096eb0cf23dc73f

build:
  number: 11
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1.5
    - cryptography
    - python-dateutil
    - requests

tests:
  - python:
      imports:
        - azure
        - azure.storage
        - azure.storage.common
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Storage Common Client Library for Python
  homepage: https://github.com/Azure/azure-storage-python

extra:
  recipe-maintainers:
    - xhochy
